<link rel="stylesheet" href="notebooks/styles.css">

<div class="title-wrap">
  <h1 class="title-main" style="font-weight: bold; font-size: 2.65rem; margin-bottom: 0.5rem;">
  Spatial Data Science Approaches to Wildfire Severity Modeling
</h1>
<h2 class="title-sub" style="font-style: italic; font-size: 1.8rem; margin-top: 0rem; margin-bottom: 0.2rem;">
  A GIS‑Driven, Tree‑Based Machine Learning Analysis of California Wildfires
</h2>
</div>

# Module 7B: *Fire Spread Class Balancing*
##### Version Number: 4.0
---
### Contents  
> *Data Preparation*
> *Automatic Class Balancing*
> *Export File*
---
### Notes

**WARNING** this module is computation heavy
- Start with a **baseline model** for comparison.
- Test with multi-classification **tree-based models** (Random Forest, XGBoost) and LGBM.
- Test and evaluate multiple class balancing strategies (No sampling, Oversampling, Undersampling)
- Compare average F1 score among all classes

---
### Inputs
- `X_spread`,`y_spread`,`model_parameters_spread` Reduced or full size Modeling sets

---
### Outputs  

`spread_best_strategy.csv` - dataframe recording best sampling strategy for each method

---
### User Created Dependencies

In [1]:
import os
import sys

# Allow import of custom modules from the parent directory
sys.path.append(os.path.abspath(os.path.join('..')))

from src.data_utils import *
from src.model_utils import *
from src.plot_utils import *

---
### Third Party Dependencies

In [2]:
# Core Python libraries
import numpy as np
import pandas as pd
import json
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing and modeling
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb

# Style
sns.set(style='whitegrid')
plt.rcParams["figure.dpi"] = 100

---

In [3]:
X = pd.read_csv('../data/processed/X_spread.csv')
y = pd.read_csv('../data/processed/y_spread.csv').squeeze()  # Load as Series

with open('../data/processed/model_parameters_spread.json', 'r') as f:
    model_parameters_spread = json.load(f)

In [4]:
model_parameters_spread

{'Random Forest': {'n_estimators': 150,
  'max_depth': 20,
  'min_samples_split': 2,
  'max_features': 'sqrt',
  'class_weight': 'balanced'},
 'XGBoost': {'objective': 'multi:softmax',
  'num_class': 5,
  'n_estimators': 200,
  'max_depth': 6,
  'learning_rate': 0.2,
  'verbosity': 0}}

## Prepare Data for Modeling - Scaling, Splitting, and Resampling

In [5]:
# Build tuned models
spread_rf = RandomForestClassifier(**model_parameters_spread['Random Forest'])
spread_xgb = xgb.XGBClassifier(**model_parameters_spread['XGBoost'])

In [6]:
models = {
    'Spread RF' : spread_rf,
    'Spread XGB' : spread_xgb,
}

#### Subset data to save processor

reform = pd.concat([X,y], axis=1)
subset = balancing_subset_df(reform, 'Target_Spread', 10000)

y = subset['Target_Spread']
X = subset.drop(columns='Target_Spread')

In [7]:
# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

## Automatic Class Balancing

To address the extreme inbalance in the dataset, multiple strategies are explored.
- **In Method Balancing** is used when applicable 
- **RandomUnderSampler** will remove random members of the majority class (Low severity) until they are balanced. This creates a much smaller dataset to model.
- **SMOTE (Synthetic Minority Over-sampling Technique)** will generate synthetic members of the minority classes. Introduces potential noise by synthetic sampling

In [8]:
sampling_strategies = ['Undersampling','No_balance','Oversampling']

all_results = []
counter = 1

for strategy in sampling_strategies:
    for name, model in models.items():
        print("running", strategy, counter, "of 6...")
        counter = counter + 1
        result = class_balancing(
            X_train, y_train, X_test, y_test,
            model, model_parameters_spread,
            sampling_strategy=strategy,
            num_classes = 5
        )
        result['Model_Label'] = name
        all_results.append(result)

# Combine into one DataFrame
all_results_df = pd.concat(all_results, axis=0).reset_index(drop=True)

running Undersampling 1 of 6...

running Undersampling 2 of 6...

running No_balance 3 of 6...

running No_balance 4 of 6...

running Oversampling 5 of 6...

running Oversampling 6 of 6...

### Format and display results

In [9]:
strategy_summary = (
    all_results_df[all_results_df['Phase'] == 'Test']
    .groupby(['Balancing','Model_Label'])['F1-Score']
    .mean()
    .reset_index()
    .sort_values(by='F1-Score', ascending=False)
)

strategy_summary_pivot = (
    strategy_summary
    .pivot(index='Model_Label', columns='Balancing', values='F1-Score')
    .sort_values(by='No_balance', ascending=False)
)

strategy_summary_pivot.style.highlight_max(axis=1, color='lightgreen')

### Display Best Strategies

In [10]:
# Find best balancing strategy per model
best_strategy = strategy_summary_pivot.idxmax(axis=1)

# Combine with model names into a new DataFrame
best_strategy_df = pd.DataFrame({
    'Model_Label': best_strategy.index,
    'Best_Strategy': best_strategy.values
})

In [11]:
best_strategy_df

  Model_Label Best_Strategy
0   Spread RF    No_balance
1  Spread XGB    No_balance

### Detailed results (ALL RESULTS)

In [12]:
all_results_df

,Class,Category,Precision,Recall,F1-Score,Phase,Model,Balancing,Model_Label
0,0,0,0.883262,0.770387,0.822848,Train,RandomForestClassifier,Undersampling,Spread RF
1,1,1,0.835426,0.872506,0.853451,Train,RandomForestClassifier,Undersampling,Spread RF
2,2,2,0.901534,0.912365,0.906817,Train,RandomForestClassifier,Undersampling,Spread RF
3,3,3,0.943289,0.964912,0.953951,Train,RandomForestClassifier,Undersampling,Spread RF
4,4,4,0.947604,0.992921,0.969731,Train,RandomForestClassifier,Undersampling,Spread RF
5,0,0,0.983937,0.791425,0.877244,Test,RandomForestClassifier,Undersampling,Spread RF
6,1,1,0.514164,0.880534,0.649229,Test,RandomForestClassifier,Undersampling,Spread RF
7,2,2,0.706543,0.912934,0.796587,Test,RandomForestClassifier,Undersampling,Spread RF
8,3,3,0.805355,0.969622,0.879887,Test,RandomForestClassifier,Undersampling,Spread RF
9,4,4,0.810575,0.997473,0.894364,Test,RandomForestClassifier,Undersampling,Spread RF
10,0,0,0.879901,0.778930,0.826027,Train,XGBClassifier,Undersampling,Spread XGB
11,1,1,0.819354,0.864421,0.841033,Train,XGBClassifier,Undersampling,Spread XGB
12,2,2,0.892163,0.902828,0.897427,Train,XGBClassifier,Undersampling,Spread XGB
13,3,3,0.947419,0.961130,0.954188,Train,XGBClassifier,Undersampling,Spread XGB
14,4,4,0.960733,0.992120,0.976168,Train,XGBClassifier,Undersampling,Spread XGB
15,0,0,0.983802,0.794949,0.879350,Test,XGBClassifier,Undersampling,Spread XGB
16,1,1,0.496928,0.882959,0.635947,Test,XGBClassifier,Undersampling,Spread XGB
17,2,2,0.693564,0.911041,0.787565,Test,XGBClassifier,Undersampling,Spread XGB
18,3,3,0.826851,0.962182,0.889398,Test,XGBClassifier,Undersampling,Spread XGB
19,4,4,0.861126,0.994946,0.923212,Test,XGBClassifier,Undersampling,Spread XGB
20,0,0,0.941561,0.970129,0.955627,Train,RandomForestClassifier,No_balance,Spread RF
21,1,1,0.846911,0.696893,0.764506,Train,RandomForestClassifier,No_balance,Spread RF
22,2,2,0.920190,0.840133,0.878332,Train,RandomForestClassifier,No_balance,Spread RF
23,3,3,0.946901,0.940275,0.943512,Train,RandomForestClassifier,No_balance,Spread RF
24,4,4,0.946093,0.983625,0.964468,Train,RandomForestClassifier,No_balance,Spread RF
25,0,0,0.945577,0.969377,0.957329,Test,RandomForestClassifier,No_balance,Spread RF
26,1,1,0.851826,0.735597,0.789457,Test,RandomForestClassifier,No_balance,Spread RF
27,2,2,0.923182,0.849211,0.884653,Test,RandomForestClassifier,No_balance,Spread RF
28,3,3,0.956658,0.944203,0.950390,Test,RandomForestClassifier,No_balance,Spread RF
29,4,4,0.945652,0.989261,0.966965,Test,RandomForestClassifier,No_balance,Spread RF
30,0,0,0.935065,0.974154,0.954208,Train,XGBClassifier,No_balance,Spread XGB
31,1,1,0.848749,0.656872,0.740503,Train,XGBClassifier,No_balance,Spread XGB
32,2,2,0.913882,0.819714,0.864176,Train,XGBClassifier,No_balance,Spread XGB
33,3,3,0.951559,0.935606,0.943495,Train,XGBClassifier,No_balance,Spread XGB
34,4,4,0.959940,0.985824,0.972683,Train,XGBClassifier,No_balance,Spread XGB
35,0,0,0.937394,0.974830,0.955746,Test,XGBClassifier,No_balance,Spread XGB
36,1,1,0.858327,0.690722,0.765457,Test,XGBClassifier,No_balance,Spread XGB
37,2,2,0.921610,0.823344,0.869710,Test,XGBClassifier,No_balance,Spread XGB
38,3,3,0.959391,0.937384,0.948260,Test,XGBClassifier,No_balance,Spread XGB
39,4,4,0.960856,0.992419,0.976383,Test,XGBClassifier,No_balance,Spread XGB
40,0,0,0.980037,0.921381,0.949795,Train,RandomForestClassifier,Oversampling,Spread RF
41,1,1,0.946146,0.983299,0.964363,Train,RandomForestClassifier,Oversampling,Spread RF
42,2,2,0.978795,0.984620,0.981696,Train,RandomForestClassifier,Oversampling,Spread RF
43,3,3,0.989814,0.992951,0.991380,Train,RandomForestClassifier,Oversampling,Spread RF
44,4,4,0.988112,0.999429,0.993737,Train,RandomForestClassifier,Oversampling,Spread RF
45,0,0,0.968024,0.929608,0.948427,Test,RandomForestClassifier,Oversampling,Spread RF
46,1,1,0.714058,0.816252,0.761743,Test,RandomForestClassifier,Oversampling,Spread RF
47,2,2,0.861212,0.896530,0.878516,Test,RandomForestClassifier,Oversampling,Spread RF
48,3,3,0.926902,0.959082,0.942718,Test,RandomForestClassifier,Oversampling,Spread RF
49,4,4,0.924662,0.992419,0.957343,Test,RandomForestClassifier,Oversampling,Spread RF
50,0,0,0.961640,0.952639,0.957115,Train,XGBClassifier,Oversampling,Spread XGB
51,1,1,0.964255,0.965949,0.965101,Train,XGBClassifier,Oversampling,Spread XGB
52,2,2,0.977942,0.977939,0.977939,Train,XGBClassifier,Oversampling,Spread XGB
53,3,3,0.989776,0.991158,0.990464,Train,XGBClassifier,Oversampling,Spread XGB
54,4,4,0.992825,0.998968,0.995886,Train,XGBClassifier,Oversampling,Spread XGB
55,0,0,0.944739,0.958134,0.951389,Test,XGBClassifier,Oversampling,Spread XGB
56,1,1,0.813571,0.719830,0.763835,Test,XGBClassifier,Oversampling,Spread XGB
57,2,2,0.875162,0.853628,0.864261,Test,XGBClassifier,Oversampling,Spread XGB
58,3,3,0.937500,0.939244,0.938371,Test,XGBClassifier,Oversampling,Spread XGB
59,4,4,0.953049,0.987366,0.969904,Test,XGBClassifier,Oversampling,Spread XGB

---

## Export File

In [13]:
best_strategy_df.to_csv('../data/processed/spread_best_strategy.csv',index=False)
print("All datasets saved successfully to ../data/processed/")

All datasets saved successfully to ../data/processed/