<link rel="stylesheet" href="notebooks/styles.css">

<div class="title-wrap">
  <h1 class="title-main" style="font-weight: bold; font-size: 2.65rem; margin-bottom: 0.5rem;">
  Spatial Data Science Approaches to Wildfire Severity Modeling
</h1>
<h2 class="title-sub" style="font-style: italic; font-size: 1.8rem; margin-top: 0rem; margin-bottom: 0.2rem;">
  A GIS‑Driven, Tree‑Based Machine Learning Analysis of California Wildfires
</h2>
</div>

# Module 7C: *Fire Damage Class Balancing*
##### Version Number: 4.0
---
### Contents  
> *Data Preparation*
> *Automatic Class Balancing*
> *Export File*
---
### Notes

**WARNING** this module is computation heavy
- Start with a **baseline model** for comparison.
- Test with multi-classification **tree-based models** (Random Forest, XGBoost) and LGBM.
- Test and evaluate multiple class balancing strategies (No sampling, Oversampling, Undersampling)
- Compare average F1 score among all classes

---
### Inputs
- `X_damage`,`y_damage`,`model_parameters_damage` Reduced or full size Modeling sets

---
### Outputs  

`damage_best_strategy` - dataframe recording best sampling strategy for each method

---
### User Created Dependencies

In [1]:
import os
import sys

# Allow import of custom modules from the parent directory
sys.path.append(os.path.abspath(os.path.join('..')))

from src.data_utils import *
from src.model_utils import *
from src.plot_utils import *

---
### Third Party Dependencies

In [2]:
# Core Python libraries
import numpy as np
import pandas as pd
import json
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing and modeling
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb

# Style
sns.set(style='whitegrid')
plt.rcParams["figure.dpi"] = 100

---

In [3]:
X = pd.read_csv('../data/processed/X_damage.csv')
y = pd.read_csv('../data/processed/y_damage.csv').squeeze()

with open('../data/processed/model_parameters_damage.json', 'r') as f:
    model_parameters_damage = json.load(f)

## Prepare Data for Modeling - Scaling, Splitting, and Resampling

In [4]:
damage_rf = RandomForestClassifier(**model_parameters_damage['Random Forest'])
damage_xgb = xgb.XGBClassifier(**model_parameters_damage['XGBoost'])

In [5]:
models = {
    'Damage RF' : damage_rf,
    'Damage XGB' : damage_xgb
}

reform = pd.concat([X,y], axis=1)
subset = balancing_subset_df(reform, 'Target_Damage', 10000,.98,.1,.1)

y = subset['Target_Damage']
X = subset.drop(columns='Target_Damage')

In [6]:
# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

## Automatic Class Balancing

To address the extreme inbalance in the dataset, multiple strategies are explored.
- **In Method Balancing** is used when applicable 
- **RandomUnderSampler** will remove random members of the majority class (Low severity) until they are balanced. This creates a much smaller dataset to model.
- **SMOTE (Synthetic Minority Over-sampling Technique)** will generate synthetic members of the minority classes. Introduces potential noise by synthetic sampling

In [7]:
sampling_strategies = ['Undersampling','No_balance','Oversampling']

all_results = []
counter = 1

for strategy in sampling_strategies:
    for name, model in models.items():
        print("running", strategy, counter, "of 6...")
        counter = counter + 1
        result = class_balancing(
            X_train, y_train, X_test, y_test,
            model, model_parameters_damage,
            sampling_strategy=strategy,
            num_classes=5
        )
        result['Model_Label'] = name
        all_results.append(result)

# Combine into one DataFrame
all_results_df = pd.concat(all_results, axis=0).reset_index(drop=True)

running Undersampling 1 of 6...

running Undersampling 2 of 6...

running No_balance 3 of 6...

running No_balance 4 of 6...

running Oversampling 5 of 6...

running Oversampling 6 of 6...

### Format and display results

In [8]:
strategy_summary = (
    all_results_df[all_results_df['Phase'] == 'Test']
    .groupby(['Balancing','Model_Label'])['F1-Score']
    .mean()
    .reset_index()
    .sort_values(by='F1-Score', ascending=False)
)

strategy_summary_pivot = (
    strategy_summary
    .pivot(index='Model_Label', columns='Balancing', values='F1-Score')
    .sort_values(by='No_balance', ascending=False)
)

strategy_summary_pivot.style.highlight_max(axis=1, color='lightgreen')

### Display Best Strategies

In [9]:
# Find best balancing strategy per model
best_strategy = strategy_summary_pivot.idxmax(axis=1)

# Combine with model names into a new DataFrame
best_strategy_df = pd.DataFrame({
    'Model_Label': best_strategy.index,
    'Best_Strategy': best_strategy.values
})

In [10]:
best_strategy_df

  Model_Label Best_Strategy
0  Damage XGB    No_balance
1   Damage RF    No_balance

### Detailed results (ALL RESULTS)

In [11]:
all_results_df

,Class,Category,Precision,Recall,F1-Score,Phase,Model,Balancing,Model_Label
0,0,0,0.996293,0.872217,0.929991,Train,RandomForestClassifier,Undersampling,Damage RF
1,1,1,0.961570,0.993321,0.977117,Train,RandomForestClassifier,Undersampling,Damage RF
2,2,2,0.962228,0.988125,0.974948,Train,RandomForestClassifier,Undersampling,Damage RF
3,3,3,0.960078,0.990601,0.975063,Train,RandomForestClassifier,Undersampling,Damage RF
4,4,4,0.961936,0.992291,0.976825,Train,RandomForestClassifier,Undersampling,Damage RF
5,0,0,1.000000,0.891135,0.942434,Test,RandomForestClassifier,Undersampling,Damage RF
6,1,1,0.633129,0.994220,0.773613,Test,RandomForestClassifier,Undersampling,Damage RF
7,2,2,0.603816,0.987156,0.749304,Test,RandomForestClassifier,Undersampling,Damage RF
8,3,3,0.626700,0.996071,0.769347,Test,RandomForestClassifier,Undersampling,Damage RF
9,4,4,0.591422,0.998095,0.742736,Test,RandomForestClassifier,Undersampling,Damage RF
10,0,0,0.997120,0.871654,0.930131,Train,XGBClassifier,Undersampling,Damage XGB
11,1,1,0.965651,0.996519,0.980827,Train,XGBClassifier,Undersampling,Damage XGB
12,2,2,0.957569,0.993236,0.975063,Train,XGBClassifier,Undersampling,Damage XGB
13,3,3,0.965594,0.989752,0.977508,Train,XGBClassifier,Undersampling,Damage XGB
14,4,4,0.964988,0.994825,0.979668,Train,XGBClassifier,Undersampling,Damage XGB
15,0,0,1.000000,0.895981,0.945137,Test,XGBClassifier,Undersampling,Damage XGB
16,1,1,0.626066,0.990366,0.767164,Test,XGBClassifier,Undersampling,Damage XGB
17,2,2,0.614857,0.987156,0.757746,Test,XGBClassifier,Undersampling,Damage XGB
18,3,3,0.646760,1.000000,0.785494,Test,XGBClassifier,Undersampling,Damage XGB
19,4,4,0.609302,0.998095,0.756679,Test,XGBClassifier,Undersampling,Damage XGB
20,0,0,0.996911,0.990649,0.993768,Train,RandomForestClassifier,No_balance,Damage RF
21,1,1,0.922046,0.977912,0.949032,Train,RandomForestClassifier,No_balance,Damage RF
22,2,2,0.955288,0.965213,0.960175,Train,RandomForestClassifier,No_balance,Damage RF
23,3,3,0.946868,0.977977,0.962086,Train,RandomForestClassifier,No_balance,Damage RF
24,4,4,0.934617,0.974429,0.953983,Train,RandomForestClassifier,No_balance,Damage RF
25,0,0,0.997647,0.992063,0.994847,Test,RandomForestClassifier,No_balance,Damage RF
26,1,1,0.935662,0.980732,0.957667,Test,RandomForestClassifier,No_balance,Damage RF
27,2,2,0.970696,0.972477,0.971586,Test,RandomForestClassifier,No_balance,Damage RF
28,3,3,0.959924,0.988212,0.973863,Test,RandomForestClassifier,No_balance,Damage RF
29,4,4,0.940109,0.986667,0.962825,Test,RandomForestClassifier,No_balance,Damage RF
30,0,0,0.997669,0.993474,0.995567,Train,XGBClassifier,No_balance,Damage XGB
31,1,1,0.944474,0.982792,0.963230,Train,XGBClassifier,No_balance,Damage XGB
32,2,2,0.963905,0.978663,0.971172,Train,XGBClassifier,No_balance,Damage XGB
33,3,3,0.950937,0.979761,0.965120,Train,XGBClassifier,No_balance,Damage XGB
34,4,4,0.967549,0.978498,0.972944,Train,XGBClassifier,No_balance,Damage XGB
35,0,0,0.997822,0.995238,0.996528,Test,XGBClassifier,No_balance,Damage XGB
36,1,1,0.960302,0.978805,0.969466,Test,XGBClassifier,No_balance,Damage XGB
37,2,2,0.960217,0.974312,0.967213,Test,XGBClassifier,No_balance,Damage XGB
38,3,3,0.976744,0.990177,0.983415,Test,XGBClassifier,No_balance,Damage XGB
39,4,4,0.977401,0.988571,0.982955,Test,XGBClassifier,No_balance,Damage XGB
40,0,0,1.000000,0.983868,0.991868,Train,RandomForestClassifier,Oversampling,Damage RF
41,1,1,0.994179,1.000000,0.997081,Train,RandomForestClassifier,Oversampling,Damage RF
42,2,2,0.997332,0.999965,0.998647,Train,RandomForestClassifier,Oversampling,Damage RF
43,3,3,0.997120,0.999928,0.998522,Train,RandomForestClassifier,Oversampling,Damage RF
44,4,4,0.995205,1.000000,0.997597,Train,RandomForestClassifier,Oversampling,Damage RF
45,0,0,0.998901,0.987551,0.993194,Test,RandomForestClassifier,Oversampling,Damage RF
46,1,1,0.909894,0.992293,0.949309,Test,RandomForestClassifier,Oversampling,Damage RF
47,2,2,0.950178,0.979817,0.964770,Test,RandomForestClassifier,Oversampling,Damage RF
48,3,3,0.943609,0.986248,0.964457,Test,RandomForestClassifier,Oversampling,Damage RF
49,4,4,0.909408,0.994286,0.949955,Test,RandomForestClassifier,Oversampling,Damage RF
50,0,0,0.999927,0.990069,0.994973,Train,XGBClassifier,Oversampling,Damage XGB
51,1,1,0.996946,1.000000,0.998470,Train,XGBClassifier,Oversampling,Damage XGB
52,2,2,0.997789,1.000000,0.998893,Train,XGBClassifier,Oversampling,Damage XGB
53,3,3,0.997337,0.999930,0.998631,Train,XGBClassifier,Oversampling,Damage XGB
54,4,4,0.998002,0.999964,0.998982,Train,XGBClassifier,Oversampling,Damage XGB
55,0,0,0.997985,0.992898,0.995435,Test,XGBClassifier,Oversampling,Damage XGB
56,1,1,0.937615,0.984586,0.960526,Test,XGBClassifier,Oversampling,Damage XGB
57,2,2,0.963702,0.974312,0.968978,Test,XGBClassifier,Oversampling,Damage XGB
58,3,3,0.967370,0.990177,0.978641,Test,XGBClassifier,Oversampling,Damage XGB
59,4,4,0.955720,0.986667,0.970947,Test,XGBClassifier,Oversampling,Damage XGB

---

## Export File

In [12]:
best_strategy_df.to_csv('../data/processed/damage_best_strategy.csv',index=False)
print("All datasets saved successfully to ../data/processed/")

All datasets saved successfully to ../data/processed/