<link rel="stylesheet" href="notebooks/styles.css">

<div class="title-wrap">
  <h1 class="title-main" style="font-weight: bold; font-size: 2.65rem; margin-bottom: 0.5rem;">
  Spatial Data Science Approaches to Wildfire Severity Modeling
</h1>
<h2 class="title-sub" style="font-style: italic; font-size: 1.8rem; margin-top: 0rem; margin-bottom: 0.2rem;">
  A GIS‑Driven, Tree‑Based Machine Learning Analysis of California Wildfires
</h2>
</div>

# Module 9B: *Fire Spread Feature Ablation*
##### Version Number: 4.0
---
### Contents  
> 1. **
> 2. **
> 3. **
---
### Notes
---
### Inputs
---
### Outputs 
---
### User Defined Dependencies

In [1]:
import os
import sys

# Allow import of custom modules from the parent directory
sys.path.append(os.path.abspath(os.path.join('..')))

from src.data_utils import *
from src.model_utils import *
from src.plot_utils import *

---
### Third Party Dependencies

In [2]:
# Core libraries
import pandas as pd
import numpy as np
import json

# Modeling libraries
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.model_selection import train_test_split

---

###  Load Data

In [3]:
X_spread = pd.read_csv('../data/processed/X_spread.csv')
y_spread = pd.read_csv('../data/processed/y_spread.csv').squeeze()  # Load as Series
details_spread = pd.read_csv('../data/processed/details_spread.csv')

pal_details = pd.read_csv('../data/processed/pal_details.csv')
pal_X = pd.read_csv('../data/processed/pal_X.csv')
pal_y = pd.read_csv('../data/processed/pal_y.csv')

best_strategy = pd.read_csv('../data/processed/spread_best_strategy.csv')

with open('model_parameters_ignition.json', 'r') as f:
    model_parameters = json.load(f)
    
with open('feature_sets.json', 'r') as f:
    feature_sets = json.load(f)

## Subset

In [4]:
reform = pd.concat([X_spread,y_spread], axis=1)
subset = subset_df(reform, 'Target_Spread', 500)

y = subset['Target_Spread']
X = subset.drop(columns='Target_Spread')

In [5]:
X_rf, y_rf = apply_balancing('RF', best_strategy, X, y)
X_xgb, y_xgb = apply_balancing('XGB', best_strategy, X, y)

## Build Models

In [6]:
RF_parameters = model_parameters['Random Forest']
XGB_parameters = model_parameters['XGBoost']

# Build tuned models
spread_xgb = xgb.XGBClassifier(**XGB_parameters)
spread_rf = RandomForestClassifier(**RF_parameters)

display(RF_parameters)
display(XGB_parameters)

{'n_estimators': 150,
 'max_depth': 15,
 'min_samples_split': 2,
 'max_features': 'log2',
 'class_weight': 'balanced'}

{'objective': 'multi:softmax',
 'num_class': 3,
 'n_estimators': 100,
 'max_depth': 4,
 'learning_rate': 0.1,
 'verbosity': 0}

In [7]:
models = {
    "XGB": spread_xgb, 
    "RF": spread_rf,
}

## SHAP

In [8]:
xgb_top_10 = get_shap(spread_xgb, X_xgb, y_xgb)
xgb_top_10

                                         0         1
0                           influence_zone  0.201566
1                          reservoir_count  0.187492
2            Palmer Drought Severity Index  0.183533
3                       road_length_meters  0.153164
4             1000-hour Dead Fuel Moisture  0.136745
5                Solar Radiation 7 Day Avg  0.136122
6  Daily Maximum Air Temperature 7 Day Avg  0.131018
7            Daily Minimum Air Temperature  0.130149
8                  Precipitation 7 Day Avg  0.091849
9                          elevation_range  0.090969

In [9]:
rf_top_10 = get_shap(spread_rf, X_rf, y_rf)
rf_top_10

 43%|=========           | 385/900 [00:11<00:14]

 46%|=========           | 415/900 [00:12<00:14]

 49%|==========          | 445/900 [00:13<00:13]

 53%|===========         | 477/900 [00:14<00:12]

 56%|===========         | 507/900 [00:15<00:11]

 60%|============        | 539/900 [00:16<00:10]

 64%|=============       | 576/900 [00:17<00:09]

 68%|==============      | 614/900 [00:18<00:08]

 72%|==============      | 652/900 [00:19<00:07]

 77%|===============     | 692/900 [00:20<00:06]

 81%|================    | 732/900 [00:21<00:04]

 86%|=================   | 773/900 [00:22<00:03]

 90%|==================  | 813/900 [00:23<00:02]

 95%|=================== | 853/900 [00:24<00:01]

 99%|===================| 887/900 [00:25<00:00]

                                    0         1
0                      influence_zone  0.014975
1  power_line_density_x_total_housing  0.012678
2       Daily Minimum Air Temperature  0.012014
3                       total_housing  0.011920
4                  road_length_meters  0.011446
5                        road_density  0.011411
6                       intermix_zone  0.010241
7    Vapor Pressure Deficit 7 Day Avg  0.010238
8                    total_population  0.009359
9                   power_line_meters  0.008913

## Ablation

In [10]:
for set_name, columns in feature_sets.items():
    print(f"{set_name}: {columns}")
    print("\n")

Water Demand: ['Actual Evapotranspiration', 'Solar Radiation', 'Solar Radiation 7 Day Avg', 'Daily Minimum Air Temperature', 'Daily Maximum Air Temperature', 'Daily Maximum Air Temperature 7 Day Avg', 'Daily Minimum Air Temperature 7 Day Avg', 'Vapor Pressure Deficit', 'Vapor Pressure Deficit 7 Day Avg', 'Wind Speed', 'Wind Speed 7 Day Avg']


Water Supply: ['Precipitation', 'Precipitation 7 Day Avg', 'Maximum Relative Humidity', 'Minimum Relative Humidity', 'Maximum Relative Humidity 7 Day Avg', 'Minimum Relative Humidity 7 Day Avg', 'Specific Humidity', '100-hour Dead Fuel Moisture', '1000-hour Dead Fuel Moisture']


Water Supply Indexes: ['Standardized Precipitation Index 30-Day', 'Standardized Precipitation Index 180-Day', 'Standardized Precipitation Evapotranspiration Index 30-Day', 'Standardized Precipitation Evapotranspiration Index 90-Day', 'Standardized Precipitation Evapotranspiration Index 180-Day', 'Palmer Drought Severity Index']


Fire Danger: ['Burning Index', 'Energy Release Component']


Social: ['total_housing', 'total_population', 'housing_density', 'population_density', 'median_income']


Temporal: ['Santa_Ana_Score', 'Season_Fall', 'Season_Spring', 'Season_Summer', 'Season_Winter']


Elevation: ['elevation_range', 'elevation_mean', 'elevation_std', 'slope_max', 'slope_range', 'slope_mean', 'slope_std', 'northness_mean', 'eastness_mean']


WUI: ['influence_zone', 'interface_zone', 'intermix_zone']


Ecoregion: ['dominant_province_percent', 'sum_province_area', 'sum_section_area', 'dominant_section_percent', 'dominant_province_description_American Semi-Desert and Desert', 'dominant_province_description_California Coastal Chaparral Forest and Shrub', 'dominant_province_description_California Coastal Range Open Woodland-Shrub-Coniferous Forest-Meadow', 'dominant_province_description_California Coastal Steppe-Mixed Forest-Redwood Forest', 'dominant_province_description_California Dry Steppe', 'dominant_province_description_Intermountain Semi-Desert', 'dominant_province_description_Intermountain Semi-Desert and Desert', 'dominant_province_description_Sierran Steppe-Mixed Forest-Coniferous Forest-Alpine Meadow', 'dominant_section_description_Central California Coast', 'dominant_section_description_Central Valley Coast Ranges', 'dominant_section_description_Colorado Desert', 'dominant_section_description_Great Valley', 'dominant_section_description_Klamath Mountains', 'dominant_section_description_Modoc Plateau', 'dominant_section_description_Mojave Desert', 'dominant_section_description_Mono', 'dominant_section_description_Northern California Coast', 'dominant_section_description_Northern California Coast Ranges', 'dominant_section_description_Northern California Interior Coast Ranges', 'dominant_section_description_Northwestern Basin and Range', 'dominant_section_description_Sierra Nevada', 'dominant_section_description_Sierra Nevada Foothills', 'dominant_section_description_Sonoran Desert', 'dominant_section_description_Southeastern Great Basin', 'dominant_section_description_Southern California Coast', 'dominant_section_description_Southern California Mountains and Valleys', 'dominant_section_description_Southern Cascades']


Land Cover: ['forest_percent', 'developed_percent', 'other_percent', 'shrub_grass_percent', 'wetlands_percent']


Interactions: ['Wind Speed_x_100-hour Dead Fuel Moisture', 'Vapor Pressure Deficit_x_Solar Radiation', 'Precipitation_x_1000-hour Dead Fuel Moisture', 'northness_mean_x_Daily Maximum Air Temperature', 'road_density_x_forest_percent', 'power_line_density_x_total_housing']


Wind Slope: ['Wind Speed_x_slope_mean', 'Wind Speed_x_slope_max', 'Wind Speed_x_northness_mean', 'Wind Speed_x_eastness_mean', 'Wind Speed_x_elevation_mean', 'Wind Speed_x_elevation_range', 'Wind Speed 7 Day Avg_x_slope_mean', 'Wind Speed 7 Day Avg_x_slope_max', 'Wind Speed 7 Day Avg_x_northness_mean', 'Wind Speed 7 Day Avg_x_eastness_mean', 'Wind Speed 7 Day Avg_x_elevation_mean', 'Wind Speed 7 Day Avg_x_elevation_range']


Others: ['NDVI_mean_difference', 'NDVI_mean_difference_has_value']

In [11]:
compare = []

for set_name, set_list in feature_sets.items():
    for model_name, model in models.items():
        print("Testing " + f"{model_name}: {set_name}")
        X_section = X.drop(columns = set_list)
        compare.append(compare_model(model, X_section, y, best_strategy,
                                     name = model_name, test_set = set_name))

Testing XGB: Water Demand

Testing RF: Water Demand

Testing XGB: Water Supply

Testing RF: Water Supply

Testing XGB: Water Supply Indexes

Testing RF: Water Supply Indexes

Testing XGB: Fire Danger

Testing RF: Fire Danger

Testing XGB: Social

Testing RF: Social

Testing XGB: Temporal

Testing RF: Temporal

Testing XGB: Elevation

Testing RF: Elevation

Testing XGB: WUI

Testing RF: WUI

Testing XGB: Ecoregion

Testing RF: Ecoregion

Testing XGB: Land Cover

Testing RF: Land Cover

Testing XGB: Interactions

Testing RF: Interactions

Testing XGB: Wind Slope

Testing RF: Wind Slope

Testing XGB: Others

Testing RF: Others

In [12]:
comparisons = pd.DataFrame(compare)
comparisons

                Test Set Model  Weighted F1  Macro F1  High Risk Recall
0           Water Demand   XGB     0.464916  0.475189          0.491071
1           Water Demand    RF     0.483351  0.493041          0.482143
2           Water Supply   XGB     0.502058  0.512356          0.508929
3           Water Supply    RF     0.479642  0.491478          0.491071
4   Water Supply Indexes   XGB     0.513837  0.520858          0.562500
5   Water Supply Indexes    RF     0.519956  0.529814          0.535714
6            Fire Danger   XGB     0.505624  0.512481          0.535714
7            Fire Danger    RF     0.486587  0.498105          0.500000
8                 Social   XGB     0.525853  0.530899          0.544643
9                 Social    RF     0.503701  0.513555          0.517857
10              Temporal   XGB     0.490715  0.496640          0.544643
11              Temporal    RF     0.504556  0.513693          0.535714
12             Elevation   XGB     0.495253  0.501076          0.535714
13             Elevation    RF     0.511015  0.520480          0.526786
14                   WUI   XGB     0.512414  0.520793          0.526786
15                   WUI    RF     0.518506  0.528992          0.491071
16             Ecoregion   XGB     0.517436  0.526275          0.544643
17             Ecoregion    RF     0.494772  0.504173          0.517857
18            Land Cover   XGB     0.504783  0.512794          0.526786
19            Land Cover    RF     0.484028  0.497734          0.517857
20          Interactions   XGB     0.505418  0.512630          0.544643
21          Interactions    RF     0.487198  0.498992          0.500000
22            Wind Slope   XGB     0.504428  0.512660          0.589286
23            Wind Slope    RF     0.495723  0.508042          0.500000
24                Others   XGB     0.497340  0.505484          0.544643
25                Others    RF     0.498429  0.509666          0.517857